package com.isaratech.signalsender.service.analysis

enum class StrategyAnalysisType {

    CCI_CORRECTION_STRATEGY,
    EMA_STRATEGY,
    GLOBAL_EXTREMA_STRATEGY,
    MACD_STRATEGY,
    MOVING_MOMENTUM_STRATEGY,
    PIVOT_POINT_REVERSAL_STRATEGY,
    RANDOM_STRATEGY,
    RSI2_STRATEGY,
    SIMPLE_RANGE_SCALPER_LONG_TERM_STRATEGY,
    SIMPLE_RANGE_SCALPER_SHORT_TERM_STRATEGY,
    SIMPLE_STRATEGY,
    ADX_STRATEGY,
    TOTO_STRATEGY,
    ANALYSIS_TOTO_STRATEGY,
    ALEX_STRATEGY,
    FINAL_TRADING_STRATEGY_V1B,
    FINAL_STRATEGY_SHORT_V2
}
